---
name: Devel-PiMPx
version: 0.8.0
author:
  - 'Ask Solem <ASKSH@cpan.org>'
abstract: The Perl-inclusive Macro Processor.
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Test::More: 0.42
dynamic_config: 0
provides:
  Devel::PiMPx:
    file: lib/Devel/PiMPx.pm
    version: 0.8.0
generated_by: Module::Build version 0.2807
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
